-- CreateTable
CREATE TABLE `MasterData` (
    `id` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `description` TEXT NULL,
    `category` VARCHAR(100) NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `textField` VARCHAR(255) NULL,
    `emailField` VARCHAR(255) NULL,
    `phoneField` VARCHAR(20) NULL,
    `urlField` VARCHAR(500) NULL,
    `searchField` VARCHAR(255) NULL,
    `textareaField` TEXT NULL,
    `richTextField` LONGTEXT NULL,
    `numberField` DECIMAL(10, 2) NULL,
    `integerField` INTEGER NULL,
    `rangeField` INTEGER NULL,
    `sliderValue` FLOAT NULL,
    `dateField` DATETIME(3) NULL,
    `timeField` VARCHAR(10) NULL,
    `dateTimeField` DATETIME(3) NULL,
    `monthField` VARCHAR(7) NULL,
    `weekField` VARCHAR(10) NULL,
    `singleSelect` VARCHAR(100) NULL,
    `multiSelect` VARCHAR(191) NULL,
    `radioSelection` VARCHAR(100) NULL,
    `checkboxGroup` VARCHAR(191) NULL,
    `switchField` BOOLEAN NOT NULL DEFAULT false,
    `checkboxField` BOOLEAN NOT NULL DEFAULT false,
    `filePath` VARCHAR(500) NULL,
    `imagePath` VARCHAR(500) NULL,
    `documentPath` VARCHAR(500) NULL,
    `colorField` VARCHAR(7) NULL,
    `ratingField` FLOAT NULL,
    `tagsField` VARCHAR(191) NULL,
    `autocompleteField` VARCHAR(255) NULL,
    `comboboxField` VARCHAR(255) NULL,
    `multiInputField` VARCHAR(191) NULL,
    `isRequired` BOOLEAN NOT NULL DEFAULT false,
    `minLength` INTEGER NULL,
    `maxLength` INTEGER NULL,
    `minValue` DECIMAL(10, 2) NULL,
    `maxValue` DECIMAL(10, 2) NULL,
    `pattern` VARCHAR(200) NULL,
    `placeholder` VARCHAR(255) NULL,
    `helpText` TEXT NULL,
    `fieldType` VARCHAR(50) NOT NULL,
    `inputMode` VARCHAR(20) NULL,
    `step` DECIMAL(10, 2) NULL,
    `multiple` BOOLEAN NOT NULL DEFAULT false,
    `dependsOn` VARCHAR(100) NULL,
    `condition` VARCHAR(200) NULL,
    `isVisible` BOOLEAN NOT NULL DEFAULT true,
    `isDisabled` BOOLEAN NOT NULL DEFAULT false,
    `fieldSize` VARCHAR(20) NULL,
    `fieldWidth` VARCHAR(20) NULL,
    `cssClass` VARCHAR(200) NULL,
    `userId` VARCHAR(191) NOT NULL,

    INDEX `MasterData_category_isActive_idx`(`category`, `isActive`),
    INDEX `MasterData_sortOrder_idx`(`sortOrder`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MasterData` ADD CONSTRAINT `MasterData_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
